### PR TITLE
BE-7219 - allow endpoint url override

### PR DESCRIPTION
**Pull request by jeffatgametime**
using this https://github.com/saidsef/aws-kinesis-local for local dev

### CODE REVIEW

**Review by ajanata — COMMENTED** [review]
:-1: why not use the already-provided `Client` config option?

**Comment by jeffatgametime** [comment]
because this is just piping what the aws client config allows

**Comment by ajanata** [comment]
It can be accomplished without having to have our own fork (which by definition is public), I'd rather avoid that if we can

**Comment by jeffatgametime** [comment]
> It can be accomplished without having to have our own fork (which by definition is public), I'd rather avoid that if we can

@ajanata this fork is already a dependency in consumers

**Review by nmwari — APPROVED** [review]

**Comment by nmwari** [comment]
It's likely that the the original repository is not maintained (see an unmerged similar change for exposing AWS Region https://github.com/tj/go-kinesis/issues/11). We're forking an ex GT employees fork of the original repository. The ex GT employees fork has also diverged from the original repository. 

So I think we are basically already maintaining are own fork, and it's unlikely that we will be able to upstream changes.

**Review by ltaziri — APPROVED** [review]

**Review by esrobinson — APPROVED** [review]

**Pull request merged**
